In [1]:
import torch
    

In [2]:
t1=torch.tensor([1,1,1,1,1,1])
t1
t2=torch.tensor([2,2,2,2,2,2])
t2


tensor([2, 2, 2, 2, 2, 2])

In [3]:
t=torch.stack((t1,t2))
t.shape

torch.Size([2, 6])

In [4]:
t.flatten()

tensor([1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2])

In [5]:
t.reshape(-1)

tensor([1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2])

In [6]:
t3=torch.tensor([[2,4]])
print(t3.shape)
t3=torch.tensor([2,4])
print(t3.shape)

torch.Size([1, 2])
torch.Size([2])


In [7]:
t=torch.tensor([[1,1,1,1],
               [2,2,2,2],
               [3,3,3,3]])

t.sum(dim=0)

tensor([6, 6, 6, 6])

In [8]:
t[0].sum(dim=0)

tensor(4)

In [9]:
t[1].sum(dim=0)

tensor(8)

In [10]:
t[2].sum(dim=0)
t[2].shape

torch.Size([4])

In [11]:
t[2].sum()

tensor(12)

In [12]:
t[0].sum(dim=1)

IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

In [14]:
t=torch.tensor([[50,180],[140,420]])
torch.argmax(t,dim=0)

tensor([1, 1])